# Generated by Django 2.2.1 on 2019-07-27 10:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField()),
                ('stop_code', models.CharField(max_length=100)),
                ('stop_name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'stops',
                'ordering': ('stop_id', 'stop_code', 'stop_name', 'geometry'),
            },
        ),
    ]
