# Generated by Django 2.2.1 on 2019-07-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_auto_20190727_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'ordering': ('stop_id', 'stop_code', 'stop_name', 'geometry'), 'verbose_name_plural': 'stops'},
        ),
        migrations.RenameField(
            model_name='stops',
            old_name='geometr',
            new_name='geometry',
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_id',
            field=models.IntegerField(max_length=3),
        ),
    ]
