# Generated by Django 2.2.1 on 2019-07-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_auto_20190727_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_id',
            field=models.IntegerField(),
        ),
    ]
