# Generated by Django 2.2.1 on 2019-07-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0004_auto_20190727_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'ordering': ('geometry', 'stop_id', 'stop_code', 'stop_name', 'stop_lat', 'stop_lon'), 'verbose_name_plural': 'stops'},
        ),
        migrations.AddField(
            model_name='stops',
            name='stop_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stops',
            name='stop_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_id',
            field=models.IntegerField(default=0.0),
        ),
    ]
