# Generated by Django 2.2.1 on 2019-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0005_auto_20190727_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_lon',
            field=models.FloatField(blank=True),
        ),
    ]
