# Generated by Django 2.2.1 on 2019-07-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0006_auto_20190727_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'ordering': ('stop_id', 'stop_code', 'stop_name', 'stop_lat', 'stop_lon'), 'verbose_name_plural': 'stops'},
        ),
    ]
