# Generated by Django 2.2.1 on 2019-07-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0007_auto_20190727_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'ordering': ('stop_id', 'stop_code', 'stop_name', 'latitude', 'longitude'), 'verbose_name_plural': 'stops'},
        ),
        migrations.RenameField(
            model_name='stops',
            old_name='stop_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='stops',
            old_name='stop_lon',
            new_name='longitude',
        ),
    ]
