# Generated by Django 2.2.1 on 2019-07-26 16:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100)),
                ('trip_id', models.IntegerField()),
                ('route_id', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'bus',
                'ordering': ('vehicle_id', 'trip_id', 'route_id', 'geometry', 'speed', 'timestamp'),
            },
        ),
    ]
