"""
Django settings for leafletwebapp project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*@9bnypstzre1d(xb$8@#$a1tl$xerv(vb-z$4m0burw(b8=-z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.gis',
    'django.contrib.staticfiles',
    'leaflet',
    'stops.apps.StopsConfig',
    'playback.apps.PlaybackConfig',
    'easy_select2',
    'crispy_forms',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'leafletwebapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR),'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'leafletwebapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'dtcdb',
        'USER': 'dtc',
        'PASSWORD': 'dtc',
        #'HOST': 'localhost',
        'HOST': '192.168.18.221',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
SELECT2_JS = 'easy_select2/vendor/select2/js/select2.min.js'
SELECT2_CSS = 'easy_select2/vendor/select2/css/select2.min.css'
SESSION_SAVE_EVERY_REQUEST = True
SELECT2_USE_BUNDLED_JQUERY = False
CRISPY_TEMPLATE_PACK = 'bootstrap4'
# SELECT2_CACHE_BACKEND = 'select2'



STATICFILES_DIRS =(
    os.path.join(BASE_DIR,'static'),
)
MAXZOOM_MAP = 19
LEAFLET_CONFIG = {


    'RESET_VIEW': False,
'MINIMAP': True,

    'DEFAULT_CENTER' : (28.613939, 77.209023),
    'MAX_ZOOM' : MAXZOOM_MAP,
    'MIN_ZOOM' : 9,
    'DEFAULT_ZOOM' :11,
    'SCALE':'both',
    'ATTRIBUTION_PREFIX' : "DTC_PROJECT",
    'TILES': [
          ('MapBox Street', 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiYWphaW4wMzk1IiwiYSI6ImNqeDczMWNkczAwcngzeHAzaDc2aGptaHIifQ.PrZuFAsV8w5ghhUhe8AF3w',
           {'attribution': '&copy; MapBox', 'maxZoom': MAXZOOM_MAP}),
          ('MapBox-Satellite', 'https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYWphaW4wMzk1IiwiYSI6ImNqeDczMWNkczAwcngzeHAzaDc2aGptaHIifQ.PrZuFAsV8w5ghhUhe8AF3w',
           {'attribution': '&copy; MapBox', 'maxZoom': MAXZOOM_MAP}),
           ('OSM', 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
     {'attribution': '&copy; OSM', 'maxZoom': MAXZOOM_MAP}),
     ],
    'PLUGINS': {
    'ZoomHome': {
        'css': ['leafletzoomhome/leaflet.zoomhome.css'],
        'js': ['leafletzoomhome/leaflet.zoomhome.min.js','leafletzoomhome/leaflet.zoomhome.js'],
        'auto-include': True,
    },
    }, 
    # 'OVERLAYS':[('MapBox-Street', '/allstops', {'attribution': '&copy; MapBox'})
    # ],
}
